name: Comment on PR

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Comment PR
        uses: mshick/add-pr-comment@v1
        with:
          message: "Thank you for your pull request!"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
