name: Retrieve PR Comments
on:
  pull_request:
    types: [closed]

jobs:
  get-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Comments
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"repo":"${{ github.repository }}", "pr_number":"${{ github.event.pull_request.number }}", "token":"${{ secrets.GITHUB_TOKEN }}"}' \
          https://ds-individualproject.onrender.com/pr_comments
